Implement user settings page #18
remsfal/remsfal-frontend pull request #141
Opened 2024-07-07 13:36 UTC by PiaSophieBe

2024-07-07 15:56 UTC, Melodycel commented
I would like to do the review.

2024-07-09 16:29 UTC, Melodycel requested changes
It looks really good! 
I tested it and everything seems to work. The tests passed as well.
I just have some questions and notes.
Why did you choose these countries? Perhaps you could integrate more European countries such as Italy, Poland, Denmark or some German-speaking countries such as Austria and Switzerland. 
You say that the data of the account will be irrevocably deleted. Have you tested this? 
Maybe you could translate "Registered Date" and "Last Login Date" under „Meine Daten“ into German (Datum der Registrierung/ Letzter Login).

2024-07-10 09:34 UTC, astanik commented
@Melodycel Thank you for your comment. Can you please use the github review functionality? ...
![grafik](https://github.com/remsfal/remsfal-frontend/assets/7569599/1c2f727d-b8e5-403c-8f0b-934aef0f50ab)


And then mark the code snippets you are talking about ...
![grafik](https://github.com/remsfal/remsfal-frontend/assets/7569599/e220909a-33cf-42b0-a6ca-7e17d26239b2)

2024-07-11 12:10 UTC, Melodycel approved these changes

2024-07-11 12:10 UTC, Melodycel commented on src/views/AccountSettingsView.vue
> +      countries: [
Looks good!

2024-07-11 12:10 UTC, Melodycel commented on src/views/AccountSettingsView.vue
> +            <p>Bist du sicher, dass du dein Konto löschen möchtest? Alle deine Daten werden unwiderruflich gelöscht.</p>
After oral consultation: It was tested.

2024-07-11 12:10 UTC, Melodycel commented on src/views/AccountSettingsView.vue
> +              <p v-if="userProfile.registeredDate"><strong>Registered Date:</strong> {{ userProfile.registeredDate }}
Looks good!

2024-07-11 12:13 UTC, Melodycel approved these changes
Everything looks really good!

2024-07-12 11:07 UTC, merged