Implementierung von Suchmaschinenoptimierungen
remsfal/remsfal-frontend pull request #179
Opened 2024-09-02 09:38 UTC by AlHassanNour

2024-09-19 12:59 UTC, AlHassanNour commented on src/views/LandingPageView.vue
JSON-LD hinzugefügt

2024-12-02 16:12 UTC, ArniBananii requested changes
Really good PR. Just have a look at my comments that i made.

2024-12-02 16:12 UTC, ArniBananii commented on public/robots.txt
> +Disallow:
Is the Disallow empty now / with no value? Shoudnt we not allow access to routes that require a login etc. ?

2024-12-02 16:12 UTC, ArniBananii commented on cypress/e2e/seo.cy.ts
> +const pages = [
Maybe we can move this const into an enum file called PageType. Then we can use them throuh out the code base instead of just this file.

2024-12-02 16:12 UTC, ArniBananii commented on test/views/LandingPageView.spec.ts
> +import LandingPage from '../../src/views/LandingPageView.vue';
Please use the Alias Path like before @/

2025-01-02 15:29 UTC, closed without merging