Create and Update Apartment View
remsfal/remsfal-frontend pull request #338
Opened 2024-12-14 21:02 UTC by AtakanYalcinx

![Bildschirmfoto 2024-12-14 um 22 01 15](https://github.com/user-attachments/assets/d0506d64-ad9e-4263-827f-d188b64ebc4a)
![Bildschirmfoto 2024-12-14 um 22 01 24](https://github.com/user-attachments/assets/a5e80af5-ba4b-44ff-a2fe-f67e770c5718)

2024-12-18 08:55 UTC, astanik commented
@AtakanYalcinx The merge of main in a feature branch has probably broken the sonar report. There are no new lines detected.

2024-12-22 19:30 UTC, ZieglerAaron reviewed
Generally you did a very good job with your KBE. There might be a bit of duplicated code in ApartmentCreationView and ApartmentUpdateView that you could combine in on new component (e.g. as in #336 ) but I don't see it as obligatory.

What do you think about my comment on the reusable form component?

2024-12-22 19:30 UTC, ZieglerAaron commented on src/components/ReusableFormComponent.vue
Should this component be in this PR, because #285 handles it?

2024-12-22 19:30 UTC, ZieglerAaron commented on src/router/index.ts
Looks good; you used the route, we agreed on at #285.

2024-12-22 19:30 UTC, ZieglerAaron commented on test/views/ApartmentCreationView.spec.ts
Because Sonar could not detect your new lines and wouldn't give me a coverage analysis  I cloned your project  tested it on my computer. Very good test coverage:
![Bildschirmfoto 2024-12-22 um 19 20 43](https://github.com/user-attachments/assets/9644104d-9527-4d10-b4a0-7eb0d8d8e4e3)

2024-12-22 19:41 UTC, ZieglerAaron requested changes
Although this works fine, please consider following project wide practice of using services to communicate with the backend.

2024-12-22 19:41 UTC, ZieglerAaron commented on src/views/ApartmentCreationView.vue
> +// Formular-Daten an Backend senden
For this we use a service. You might want to have a look at the ProjectService and transfer the appartment-functions to a new AppartmentService.ts.

2024-12-22 19:41 UTC, ZieglerAaron commented on src/views/ApartmentUpdateView.vue
> +// Apartment-Daten laden
This would also be handled in your new AppartmentService.ts.

2024-12-24 13:46 UTC, AtakanYalcinx commented on src/components/ReusableFormComponent.vue
Yes  my  bad, i am  so  sorry!

2025-01-08 10:53 UTC, astanik commented
@AtakanYalcinx Is there a reason why you didn't implement the review?

2025-01-08 15:56 UTC, astanik approved these changes
Unfortunately, this pull request was no longer processed after the review. It will still be merged and should be improved with a new issue.

2025-01-08 15:57 UTC, merged

2025-01-08 22:35 UTC, ZieglerAaron commented on src/views/ApartmentCreationView.vue
> +// Formular-Daten an Backend senden
I created #378 for this.