Implement project member management on the project settings view
remsfal/remsfal-frontend pull request #346
Opened 2024-12-16 15:53 UTC by antjeble

This implements Issue #6 
Should look like this
![image](https://github.com/user-attachments/assets/dc4b7a36-2c60-4c7e-9744-29f6b976ceba)

2024-12-31 11:38 UTC, RybochkinaMarina requested changes

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/views/ProjectSettingsView.vue
> +      />
Hier könnte man stattdessen spezielle Komponente InputText von PrimeVue benutzen, die schon gestylt ist.

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/views/ProjectSettingsView.vue
> +      </select>
Das kann man durch die PrimeVue-Komponente Dropdown ersetzen, die die Suchbarkeit ermöglicht.

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/views/ProjectSettingsView.vue
> +      <button @click="addMember" class="create-btn">erstellen</button>
Man sollte die PrimeVue-Komponente Button benutzen, die schon Styles und Interaktionen integriert hat.

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/views/ProjectSettingsView.vue
> +}
Statt benutzerdefiniertem CSS sollten die PrimeVue-Styles genutzt werden. Das kann durch PrimeVue-Komponenten mit severity- oder styleClass-Props ersetzt werden.

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/services/ProjectMemberService.ts
> +        }
Fehler wird nicht spezifisch behandelt, es gibt keine Unterscheidung zwischen server error, network error usw.

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/services/ProjectMemberService.ts
> +    }
Die Methode könnte durch Caching optimiert werden, um unnötige Netzwerkaufrufe zu vermeiden.

2024-12-31 11:38 UTC, RybochkinaMarina commented on src/services/ProjectMemberService.ts
> +        }
Implementiere ein Rollback, um den vorherigen Zustand bei fehlgeschlagenen Updates wiederherzustellen.

2025-01-02 15:41 UTC, astanik commented
@thienlnguyen Thank you for your comments. However, your review was requested in https://github.com/remsfal/remsfal.github.io/pull/74

2025-01-05 13:08 UTC, antjeble commented on src/views/ProjectSettingsView.vue
> +      />
wird jetzt verwendet
![image](https://github.com/user-attachments/assets/fd21c63f-eee6-497d-9190-5ea4c3c41641)

2025-01-05 13:08 UTC, antjeble commented on src/views/ProjectSettingsView.vue
> +      </select>
wird jetzt verwendet

2025-01-05 13:09 UTC, antjeble commented on src/views/ProjectSettingsView.vue
> +      <button @click="addMember" class="create-btn">erstellen</button>
wird jetzt verwendet

2025-01-05 13:10 UTC, antjeble commented on src/views/ProjectSettingsView.vue
> +      <select v-model="newMemberRole">
wurde angepasst und ist jetzt angezeigt

2025-01-05 13:11 UTC, antjeble commented on src/views/ProjectSettingsView.vue
> +  } catch (error) {
error handling insgesamt verbessert

2025-01-05 13:11 UTC, antjeble commented on src/services/ProjectMemberService.ts
> +        }
rollback wurde implementiert

2025-01-05 13:12 UTC, antjeble commented on src/services/ProjectMemberService.ts
> +        }
error handling insgesamt verbessert

2025-01-05 13:35 UTC, antjeble commented
In the ProjectMemberModel.java class, six user roles are defined, but the corresponding Liquibase changeset allows only four of these roles in the database. As a result, the roles CONTRACTOR and TENANCY cannot be properly stored or utilized in the database.
I decided to still add CONTRACTOR and TENANCY in the ProjectSettingsView.vue and open an Issue for adding the missing roles because the mismatch already exists in the backend. 
https://github.com/remsfal/remsfal-backend/issues/292

2025-01-05 19:20 UTC, RybochkinaMarina approved these changes
Die PrimeVue-Komponenten wurden statt die plain-HTML Elementen eingesetzt.

2025-01-06 06:40 UTC, astanik approved these changes

2025-01-06 06:40 UTC, merged