Editing and Displaying Task Components
remsfal/remsfal-frontend pull request #348
Opened 2024-12-16 20:53 UTC by IbrahimDembaSeck

![Screen I](https://github.com/user-attachments/assets/9ad1e432-32bb-4f81-8379-0fba490903cb)
![Screen II](https://github.com/user-attachments/assets/d98cac8d-9ecb-472b-ae9b-f3ac3cbc5b07)
![Screen III](https://github.com/user-attachments/assets/04b434cc-66e3-43e8-90c8-aff203ed9231)

2024-12-25 23:01 UTC, nasrwihtw requested changes
Here are a few suggestions for improvement taskEdit

2024-12-25 23:04 UTC, nasrwihtw requested changes

2024-12-25 23:04 UTC, nasrwihtw commented on src/views/TaskEdit.vue
> +};
You’re using loading as a ref to manage the task fetching state. You can make the logic cleaner by using Vue's lifecycle hooks to set the loading state accordingly.

example:  onMounted

2025-01-07 03:28 UTC, IbrahimDembaSeck commented on src/router/index.ts
> +                path: 'tasks/:taskId',
I did it in my commits . I'm sorry

2025-01-07 03:29 UTC, IbrahimDembaSeck commented on src/services/TaskService.ts
> +  static getTask: any;
You're right I deleted it

2025-01-07 03:33 UTC, IbrahimDembaSeck commented on src/services/TaskService.ts
> +        status: status,
"I implemented the Owner feature. However, as you mentioned, there is an issue with the backend, which is why I couldn't get it to work as expected. You can still see the Owner displayed (frontend only) , but I marked it as 'Nicht angegeben'.

2025-01-07 03:34 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +const startEditing = (row: any, field: string) => {
I implemented it . Thanks for the suggestion

2025-01-07 03:34 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +const stopEditing = (row: any) => {
I implemented it

2025-01-07 04:52 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +  }
Did it

2025-01-07 04:54 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +    alert('Die Aufgabe wurde erfolgreich gespeichert!');
Location.reload is removed and Loading is seen until you get the notification

2025-01-07 04:56 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +}
I have marked these elements as 'Nicht angegeben ' and you see these  if you expand the table

2025-01-07 04:57 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +};
Changed it

2025-01-07 07:36 UTC, IbrahimDembaSeck commented
xx

2025-01-07 22:08 UTC, IbrahimDembaSeck commented on src/views/TaskEdit.vue
> +</template>
I have successfully implemented the specified requirements as follows:

- Validation of User Inputs 
- Extending Functionality of Table Visualization: You can expand the Table to see more details 
- Testing for Task Edit : done with cypress, that's why the testing coverage is 0.

2025-01-08 15:21 UTC, astanik approved these changes

2025-01-08 15:21 UTC, astanik commented on src/services/TaskService.ts
> +        status: status,
Please create a new issue for this feature/bug.

2025-01-08 15:23 UTC, merged