Enhancement - View zur Verwaltung von Dienstleistern
remsfal/remsfal-frontend pull request #355
Opened 2024-12-17 15:49 UTC by ElsarChabaev

##Beschreibung

Dieses Enhancement erweitert das Verwalter-Dashboard um eine zentrale Ansicht zur Verwaltung von Dienstleisterdaten. Diese Ansicht ermöglicht es Verwaltern, Dienstleister effizient zu **registrieren, löschen, bearbeiten, relevante Informationen einzusehen** (zum Beispiel Name, Firma, Kontaktdaten) und bestehende **Dienstleister zu offenen Aufträgen hinzuzufügen**.

Innerhalb des Dashboards gibt es eine Navigationsstruktur mit Tabs, die den Zugriff auf spezifische Verwaltungsansichten ermöglicht. Der Fokus dieses Enhancements liegt auf der Verwaltung der Dienstleisterdaten.

Für die Dienstleistertabelle ist eine **Suchfunktion** vorgesehen, die dynamisch nach jeder Eingabe **Dienstleister in der Tabelle** filtert, diese anzeigt und die mit der Eingabe **übereinstimmenden Zeichen hervorhebt**.

In der Aufträge-Tabelle wird eine **Autovervollständigungsfunktion** beim Zuordnen von Dienstleistern zu offenen Aufträgen eingebaut, basierend auf einer gemockten Backend-Datenquelle. Das Backend wird jedoch nicht implementiert, bleibt aber für zukünftige Erweiterungen vorbereitet.

##Diskussion
Kein Kommentar

##Motivation
Die Einführung eines speziellen Dienstleisterdaten-Dashboards vereinfacht die zentrale Verwaltung der Dienstleister und bildet die Grundlage für zukünftige Erweiterungen. Die Verwalterrolle spielt eine zentrale Rolle bei der effizienten Verwaltung des Systems und übernimmt exklusive Aufgaben wie die Registrierung von Dienstleistern. Mit diesem Dashboard wird die Verwalterrolle klar definiert und benutzerfreundlich umgesetzt.

##Details

**Details:**

**Dashboard für Verwalter zur Verwaltung von Dienstleistern:**

- [x]  In der zentralen Navigationsstruktur soll ein Reiterpunkt namens "Dienstleisterdaten" mit einem passenden Label in Manager.Menu.vue erstellt werden.
- [x]  In der index.ts soll eine "providers"-Route erstellt werden, die zur zugehörigen View führt.
- [x] Eine View namens "ProviderView.view" wird unter src/views erstellt.

**ProviderView:**

![image](https://github.com/user-attachments/assets/2f488049-1e3f-459d-af84-4480ebbd9c7f)

**Tabelle der bestehenden Dienstleister mit Implementierung der CRUD-Funktionen:**

![image](https://github.com/user-attachments/assets/89ca2f5e-430a-4714-8ee7-5f9ec78b8ae3)

- [x]  Erstellen: Alle Spalten müssen ausgefüllt sein (mit Speichern- und Abbrechen-Funktion).
![image](https://github.com/user-attachments/assets/026c0195-ec34-4f3a-b309-c1bdf0ce9128)

- [x] Lesen: Die relevanten Informationen sollen der Tabelle zu entnehmen sein.

- [x] Bearbeiten: Bestehende Dienstleisterdaten können bearbeitet werden (mit Speichern- und Abbrechen-Funktion):
![image](https://github.com/user-attachments/assets/035f64c0-3c3d-4760-a1ea-dec5fe600533)

![image](https://github.com/user-attachments/assets/31af4f7b-7eb0-46ec-a312-8a408997dcf6)

- [x] Löschen: Dienstleister können gelöscht werden (mit Speichern- oder Abbrechen-Funktion):

![image](https://github.com/user-attachments/assets/31cdda9c-e414-4138-acdc-72b285465288)

![image](https://github.com/user-attachments/assets/8f1e0dcb-b6ae-4682-acb8-0ec489f32dd3)

- [x] Suchleiste mit Validierungsfunktion: Passende Übereinstimmungen werden fett markiert und hervorgehoben, andere ausgeblendet:

![image](https://github.com/user-attachments/assets/91112933-a061-40ca-8ccb-f6080b895390)

![image](https://github.com/user-attachments/assets/c1eb4fbb-114c-4234-a5d1-78b8d2f052eb)

- [x] Zehn gemockte Dienstleister sind bereits in der Tabelle vorhanden:

**Aufträge-Tabelle:**

![image](https://github.com/user-attachments/assets/73b2a6b3-250d-420a-8803-f2637d827d41)

- [x] Enthält gemockte Aufträge.

- [x] Zu jedem Auftrag kann ein bestehender Dienstleister hinzugefügt werden:

![image](https://github.com/user-attachments/assets/3e8d1d5e-56a6-4947-84c7-660b2fc80460)

- [x] Beim Eintragen des Dienstleisters hilft eine Autovervollständigungsfunktion beim Ausfüllen mit den Namen existierender Dienstleister:

![image](https://github.com/user-attachments/assets/516a1ec6-96ca-4bd3-8d8d-9ed0264ba187)

![image](https://github.com/user-attachments/assets/2276b54e-7509-44b4-a8c4-a0c934baa10f)

**Anforderungen an Tabellen und Methoden:**

 - [x] Tabellen sind scrollbar und zeigen standardmäßig die ersten fünf Einträge:
 
 
![image](https://github.com/user-attachments/assets/fe09247c-9382-4e3f-874d-cb2dcbbbfda7)

 
 - [x] Bestätigungs-Popups bei erfolgreichen Durchführungen von Aktionen:
 
![image](https://github.com/user-attachments/assets/27f9813b-ac4e-4006-b0fd-96ddfde7150a)

- [x]  Hinweis-Popups bei Fehlern auf der Verwalter-Seite:

![image](https://github.com/user-attachments/assets/71a60121-9eee-4357-9c00-018f98a203b9)

![image](https://github.com/user-attachments/assets/bac364bf-0cdd-4fa0-9fe9-7f8e90c7e33a)

- [x] Das Dashboard kann zukünftig um weitere Verwaltungsfunktionen wie Mieterverwaltung, Berichte und Statistiken erweitert werden.

**Akzeptanzkriterien:**
- Das Verwalter-Dashboard ist funktional und enthält eine Navigationsstruktur mit mindestens einem Tab für „Dienstleister“.
- In der Dienstleister-View können Verwalter Dienstleister registrieren, löschen, kontaktieren und zuweisen.
- Die Autovervollständigungsfunktion zeigt passende Dienstleister basierend auf Eingaben an, wobei die Daten aus einer gemockten Liste stammen.
- Das Backend bleibt unberührt und vorbereitet für zukünftige Erweiterungen.

2024-12-30 21:50 UTC, s0571584 requested changes

2024-12-30 21:50 UTC, s0571584 commented on src/views/ProviderView.vue
> +const orders = ref([
mock Daten vielleicht auf andere Klasse verlagern, damit es übersichtlicher ist

2024-12-30 21:50 UTC, s0571584 commented on src/views/ProviderView.vue
> +const assignProviderToOrder = (orderId: number, providerId: number) => {
Mehr try & catch Blöcke einbinden um Fehler leichter zu differenzieren und bugs leichter zu lokalisieren. Diese Funktion wäre eine gute Möglichkeit dafür

2024-12-30 21:50 UTC, s0571584 commented on src/layout/AppMenuItem.vue
>  import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
Wenn ich mit Strg + F nach dem Import FontAwesomeIcon suche, sehe Ich, dass es nicht genutzt wird. (Vielleicht stimmt was mit dem Browser/Github nicht).

2024-12-30 21:50 UTC, s0571584 commented on src/views/ProviderView.vue
> +const highlightMatch = (text, query) => {
Füge Annotationen für die Parameter hinzu, um TypeScript Fehler wie diese zu vermeiden. Ungefähr so:

const highlightMatch = (text: string, query: string) => {..

2025-01-08 18:15 UTC, astanik commented
The design doesn't look bad at all, but it lacks of various basic technical features. The code is not TypeScript compliant. The build is not running. No PrimeVue components are used and there has been no further development after the review. Therefore the PR is closed without a merge.

2025-01-08 18:15 UTC, closed without merging