adjust AccountSettingsView
remsfal/remsfal-frontend pull request #356
Opened 2024-12-17 17:47 UTC by thienlnguyen

- Users can update their profile information directly without requiring an additional button.
- Input fields now include validation.
- Mandatory fields are clearly marked.
- Changes can be discarded if needed.
- Unit tests using Vitest have been implemented

2024-12-30 10:49 UTC, AliceKitchkin requested changes
### Review des Pull Requests #356 
Alle Hinweise und Notizen wurden, für eine bessere Verständlichkeit, in den genauen Codezeilen hinterlegt. Dabei gibt es die Abschnitte "Hinweise für Thien", welche Vorschläge für Änderungen enthalten, und "Notizen", welcher zur Verständlichkeit des Codes für den Reviewer beitagen soll.

**Ansicht vorher:**
<img width="960" alt="Benutzerprofil_Bearbeiten_leer" src="https://github.com/user-attachments/assets/2cd63b25-c20c-441a-a37a-6263d1a597e6" />

**Ansicht nachher:**
<img width="957" alt="Benutzerprofil_Ansicht" src="https://github.com/user-attachments/assets/1decb4db-7fa9-4f4b-9e72-fc8778465314" />

### Allgemeine Anmerkungen
**Code Kommentare:**
Für die schnelle Verständlichkeit und bessere Lesbarkeit fehlen im Code Kommentare, diese sollten sinnvoll und einheitlich in Englisch hinterlegt werden.

**Commit Messages:**
Vor dem Merge wird im Regelfall nur der "Diff" betrachtet, dennoch sollten die Commit Messages in Zukunft etwas ausführlicher dokumentiert werden.

**Testabdeckung:**
Durch SonarCloud ergab sich eine Testabdeckung von 77,8%, 80% sind erforderlich. Es könnten folgende Tests ergänzt werden:
- Testen, ob das Speichern des Profils verhindert wird, wenn eine ungültige Telefonnummer eingegeben wird
- Testen, ob die Erfolgs- und Fehler-Pop-Ups korrekt angezeigt werden, wenn das Speichern erfolgreich ist oder fehlschlägt

**Test Mocking:**
Die Methoden werden direkt auf `wrapper.vm.$options` gemockt. Eventuell sollten diese Methoden lieber auf der Instanz `wrapper.vm` gemockt werden, um sicherzustellen, dass die gemockten Methoden tatsächlich aufgerufen werden.
```suggestion
    vi.spyOn(wrapper.vm, 'fetchUserProfile').mockResolvedValue({ ...
```

**Rebase:**
Achte darauf, ein Rebase durchzuführen, bevor du ein PR erstellst. Dadurch vermeidest du irgendwelche Merge-Konflikte, weil du auf dem neuesten Stand bist.

### Zu erfüllende Anforderungen
Im Issue wurden folgende Anforderungen gelistet und erfüllt/nicht erfüllt:
- [x] Users can update their profile information directly without requiring an additional button. _-> Erfüllt: Benutzer gelangt direkt zur Editoransicht_
- [ ] Input fields now include validation. _-> Teilweise erfüllt: Fehlermeldungen werden teilweise nicht korrekt ein- und ausgeblendet. Siehe Review in Codezeilen_
- [X] Mandatory fields are clearly marked. _-> Erfüllt: Schwarze Sternchen_
- [X] Changes can be discarded if needed. _-> Erfüllt: Abbrechen-Button_
- [X] Unit tests using Vitest have been implemented _-> Erfüllt: Tests laufen durch ohne Error_

### Ergänzende Anforderungen
Es haben sich beim Review ein paar (weitere) Kann-Anforderungen ergeben.

**Nice to have: Logik**
- E-Mail ändern können
- Eingabeüberprüfung von Stadt und Bundesland (z.B. auf Korrektheit oder keine Zahlen)
- Eingabeüberprüfung der Adresse, sollte mindestens eine Zahl enthalten für die Hausnummer

**Nice to have: Design**
- Pflichtfelder-Sternchen rot markieren statt schwarz
- Abstand zwischen den Buttons "Speichern" und "Abbrechen" einügen
- Abstand zwischen allen Buttons und der horizontalen Linie einfügen
<img width="960" alt="Abstand_Buttons" src="https://github.com/user-attachments/assets/243a1533-d4af-4c72-84d1-1daef863ad48" />

2024-12-30 10:49 UTC, AliceKitchkin commented on test/views/AccountSettingsView.spec.ts
>      expect(wrapper.exists()).toBe(true);
### Hinweise für Thien
Der Test scheint noch unvollständig zu sein. Sollte die Vervollständigung innerhalb des Issue-Scopes liegen, müsste der Test noch ergänzt werden.

2024-12-30 10:49 UTC, AliceKitchkin commented on test/views/AccountSettingsView.spec.ts
Jeder Test sollte eine kurze Beschreibung als Kommentar bekommen. Die hier hinzugefügten Tests decken ein paar Edge Cases ab, jedoch noch nicht weitere mögliche Szenarien. Je nach Issue-Scope, sollte das mit dem Dozenten geklärt und die Tests eventuell erweitert werden.

2025-01-06 16:29 UTC, AliceKitchkin commented
@thienlnguyen please read my review and the requested changes :)

2025-01-06 21:25 UTC, thienlnguyen commented on test/views/AccountSettingsView.spec.ts
>      expect(wrapper.exists()).toBe(true);
Hi Alice,
die von dir markierten Codezeilen im beforeEach-Block dienen dazu, die Methoden saveProfile(), fetchUserProfile() und validateAddress() zu mocken. Die Mocks ermöglichen die Methoden später in den spezifischen Tests zu überwachen.

Die Tests für diese Funktionen sind bereits an den folgenden Stellen implementiert: saveProfile() in Zeile 96, fetchUserProfile() in Zeile 59 und validateAddress() in Zeile 116.

2025-01-06 22:09 UTC, thienlnguyen commented on src/views/AccountSettingsView.vue
> +  try {
Hi Alice, 
die Felder werden bereits validiert, wenn Änderungen vorgenommen werden. Ich habe den Code nun so angepasst, dass der Speichern-Button disabled wird, sobald Fehlermeldungen erscheinen.

2025-01-07 12:56 UTC, AliceKitchkin commented on src/views/AccountSettingsView.vue
> +function validateAddress(address: Partial<Address>): boolean {
- [x] done

2025-01-07 13:05 UTC, AliceKitchkin approved these changes

2025-01-07 13:05 UTC, AliceKitchkin commented on src/views/AccountSettingsView.vue
> +    errorMessage.value.zip = 'Bitte eingeben!';
- [x] done

2025-01-07 13:05 UTC, AliceKitchkin commented on test/views/AccountSettingsView.spec.ts
- [x] done

2025-01-07 13:05 UTC, AliceKitchkin commented on test/views/AccountSettingsView.spec.ts
>      expect(wrapper.exists()).toBe(true);
- [x] done

2025-01-07 13:05 UTC, AliceKitchkin commented on src/views/AccountSettingsView.vue
> +  try {
- [x] done

2025-01-07 13:06 UTC, AliceKitchkin commented
@astanik please take a look, the code is ready to merge for me 👍

2025-01-08 10:42 UTC, merged